export const ADD_EVENT = "ADD_EVENT";
export const EDIT_EVENT = "EDIT_EVENT";
export const DELETE_EVENT = "DELETE_EVENT";
export const CLEAR_EVENTS = "CLEAR_EVENTS";

export const FETCH_EVENTS_REQUEST = "FETCH_EVENTS_REQUEST";
export const FETCH_EVENTS_SUCCESS = "FETCH_EVENTS_SUCCESS";
export const FETCH_EVENTS_FAILURE = "FETCH_EVENTS_FAILURE";

export const ADD_NEW_EVENT_SERVER_REQUEST = "ADD_NEW_EVENT_SERVER_REQUEST";
export const ADD_NEW_EVENT_SERVER_FAILURE = "ADD_NEW_EVENT_SERVER_FAILURE";

export const EDIT_EVENT_SERVER_REQUEST = "EDIT_EVENT_SERVER_REQUEST";
export const EDIT_EVENT_SERVER_FAILURE = "EDIT_EVENT_SERVER_FAILURE";
