export const SET_IS_CHAT_NOTIFY_ON = "SET_IS_CHAT_NOTIFY_ON";
export const SET_IS_CHAT_NOTIFY_OFF = "SET_IS_CHAT_NOTIFY_OFF";
export const SET_IS_CHAT_NOTIFY_INNER_OFF = "SET_IS_CHAT_NOTIFY_INNER_OFF";
