export const SET_IS_CHAT_NOTIFY_ON = "SET_IS_CHAT_NOTIFY_ON";
export const SET_IS_CHAT_NOTIFY_OFF = "SET_IS_CHAT_NOTIFY_OFF";
export const SET_IS_OPEN = "SET_IS_OPEN";
export const REMOVE_EVENT = "REMOVE_EVENT";
