export const FETCH_COLUMNS_REQUEST = "FETCH_COLUMNS_REQUEST";
export const FETCH_COLUMNS_SUCCESS = "FETCH_COLUMNS_SUCCESS";
export const FETCH_COLUMNS_FAILURE = "FETCH_COLUMNS_FAILURE";

export const ADD_COLUMN_REQUEST = "ADD_COLUMN_REQUEST";
export const ADD_COLUMN_SUCCESS = "ADD_COLUMN_SUCCESS";
export const ADD_COLUMN_FAILURE = "ADD_COLUMN_FAILURE";

export const EDIT_COLUMN_REQUEST = "EDIT_COLUMN_REQUEST";
export const EDIT_COLUMN_SUCCESS = "EDIT_COLUMN_SUCCESS";
export const EDIT_COLUMN_FAILURE = "EDIT_COLUMN_FAILURE";

export const DELETE_COLUMN_REQUEST = "DELETE_COLUMN_REQUEST";
export const DELETE_COLUMN_SUCCESS = "DELETE_COLUMN_SUCCESS";
export const DELETE_COLUMN_FAILURE = "DELETE_COLUMN_FAILURE";

export const SET_CURRENT_COLUMN_ID_AND_TITLE =
  "SET_CURRENT_COLUMN_ID_AND_TITLE";

export const DELETE_COLUMN_BY_BOARD = "DELETE_COLUMN_BY_BOARD";
