export const ADD_NEW_COLUMN_ORDER_LOCAL = "ADD_NEW_COLUMN_ORDER_LOCAL";
export const ADD_NEW_COLUMN_TO_COLUMN_ORDER_LOCAL =
  "ADD_NEW_COLUMN_TO_COLUMN_ORDER_LOCAL";
export const DELETE_COLUMN_ORDER_BY_BOARD_LOCAL =
  "DELETE_COLUMN_ORDER_BY_BOARD_LOCAL";
export const GET_COLUMN_ORDER_BY_BOARD_LOCAL =
  "GET_COLUMN_ORDER_BY_BOARD_LOCAL";
export const CHANGE_COLUMN_ORDER_LOCAL = "CHANGE_COLUMN_ORDER_LOCAL";
export const COLUMN_ORDER_API_URL =
  "https://intense-garden-79464.herokuapp.com/api/v1/columnorder";
