export const FETCH_COLUMN_ORDER_REQUEST = "FETCH_COLUMN_ORDER_REQUEST";
export const FETCH_COLUMN_ORDER_SUCCESS = "FETCH_COLUMN_ORDER_SUCCESS";
export const FETCH_COLUMN_ORDER_FAILURE = "FETCH_COLUMN_ORDER_FAILURE";

export const UPDATE_COLUMN_ORDER_REQUEST = "UPDATE_COLUMN_ORDER_REQUEST";
export const UPDATE_COLUMN_ORDER_SUCCESS = "UPDATE_COLUMN_ORDER_SUCCESS";
export const UPDATE_COLUMN_ORDER_FAILURE = "UPDATE_COLUMN_ORDER_FAILURE";

export const COLUMN_ORDER_API_URL =
  "https://intense-garden-79464.herokuapp.com/api/v1/columnorder";
export const UPDATE_COLUMN_ORDER_LOCAL = "UPDATE_COLUMN_ORDER_LOCAL";
