// Boards types
export const ADD_BOARD_REQUEST = "ADD_BOARD_REQUEST";
export const ADD_BOARD_SUCCESS = "ADD_BOARD_SUCCESS";
export const ADD_BOARD_FAILURE = "ADD_BOARD_FAILURE";

export const EDIT_BOARD_REQUEST = "EDIT_BOARD_REQUEST";
export const EDIT_BOARD_SUCCESS = "EDIT_BOARD_SUCCESS";
export const EDIT_BOARD_FAILURE = "EDIT_BOARD_FAILURE";

export const DELETE_BOARD_REQUEST = "DELETE_BOARD_REQUEST";
export const DELETE_BOARD_SUCCESS = "DELETE_BOARD_SUCCESS";
export const DELETE_BOARD_FAILURE = "DELETE_BOARD_FAILURE";

export const FETCH_BOARD_REQUEST = "FETCH_BOARD_REQUEST";
export const FETCH_BOARD_SUCCESS = "FETCH_BOARD_SUCCESS";
export const FETCH_BOARD_FAILURE = "FETCH_BOARD_FAILURE";

export const SET_CURRENT_BOARD_ID_AND_TITLE = "SET_CURRENT_BOARD_ID_AND_TITLE";
