export const FETCH_BOARDS_REQUEST = "FETCH_BOARDS_REQUEST";
export const FETCH_BOARDS_SUCCESS = "FETCH_BOARDS_SUCCESS";
export const FETCH_BOARDS_FAILURE = "FETCH_BOARDS_FAILURE";

export const CLEAR_BOARDS = "CLEAR_BOARDS";

export const ADD_NEW_BOARD_LOCAL = "ADD_NEW_BOARD_LOCAL";
export const ADD_NEW_BOARD_SERVER = "ADD_BOARD_SERVER";
export const ADD_NEW_BOARD_SERVER_FAILURE = "ADD_NEW_BOARD_SERVER_FAILURE";

export const EDIT_BOARD_LOCAL = "EDIT_BOARD_LOCAL";
export const EDIT_BOARD_SERVER = "EDIT_BOARD_SERVER";
export const EDIT_BOARD_SERVER_FAILURE = "EDIT_BOARD_SERVER_FAILURE";

export const DELETE_BOARD_LOCAL = "DELETE_BOARD_LOCAL";
export const DELETE_BOARD_SERVER = "DELETE_BOARD_SERVER";
export const DELTE_BOARD_SERVER_FAILURE = "DELTE_BOARD_SERVER_FAILURE";

export const ADD_COLUMN_TO_COLUMNS_ORDER_LOCAL =
  "ADD_COLUMN_TO_COLUMNS_ORDER_LOCAL";
export const REMOVE_COLUM_FROM_COLUMNS_ORDER_LOCAL =
  "REMOVE_COLUM_FROM_COLUMNS_ORDER_LOCAL";
export const CHANGE_COLUMNS_ORDER_LOCAL = "CHANGE_COLUMNS_ORDER_LOCAL";

export const ENTER_SEARCH_TEXT = "ENTER_SEARCH_TEXT";
export const SET_CURRENT_BOARD_DATA = "SET_CURRENT_BOARD_DATA";

export const ADD_MEMBER_TO_BOARD_SUCCESS = "ADD_MEMBER_TO_BOARD_SUCCESS";
export const ADD_MEMBER_TO_BOARD_FAILURE = "ADD_MEMBER_TO_BOARD_FAILURE";
