export const ADD_NEW_BOARD_LOCAL = "ADD_NEW_BOARD_LOCAL";
export const ADD_NEW_BOARD_SERVER = "ADD_BOARD_SERVER";
export const ADD_NEW_BOARD_SERVER_FAILURE = "ADD_NEW_BOARD_SERVER_FAILURE";
export const SET_CURRENT_BOARD_DATA = "SET_CURRENT_BOARD_DATA";
export const EDIT_BOARD_LOCAL = "EDIT_BOARD_LOCAL";
export const EDIT_BOARD_SERVER = "EDIT_BOARD_SERVER";
export const EDIT_BOARD_SERVER_FAILURE = "EDIT_BOARD_SERVER_FAILURE";
export const ADD_COLUMN_TO_COLUMNS_ORDER_LOCAL =
  "ADD_COLUMN_TO_COLUMNS_ORDER_LOCAL";
export const CHANGE_COLUMNS_ORDER_LOCAL = "CHANGE_COLUMNS_ORDER_LOCAL";
export const REMOVE_COLUM_FROM_COLUMNS_ORDER_LOCAL =
  "REMOVE_COLUM_FROM_COLUMNS_ORDER_LOCAL";
export const DELETE_BOARD_LOCAL = "DELETE_BOARD_LOCAL";
export const DELETE_BOARD_SERVER = "DELETE_BOARD_SERVER";
export const DELTE_BOARD_SERVER_FAILURE = "DELTE_BOARD_SERVER_FAILURE";
export const ENTER_SEARCH_TEXT = "ENTER_SEARCH_TEXT";
